---
- hosts: test
  connection: local
  name: Configure Server Power Setting
  gather_facts: False

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Configure Server Power Setting
    dellemc_change_power_state:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
       change_power: "PushPowerButton"

    tags:
      - power_state

