---
- hosts: INTEL14G
  connection: local
  name: Reset iDRAC
  gather_facts: False
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - name: Reset iDRAC
    dellemc_idrac_reset:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"

    tags:
      - idrac_reset
