---
- hosts: 4SOCKET
  connection: local
  name: Configure Server Power Setting
  gather_facts: False
   
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Configure Server Power Setting - GracefulRestart
    dellemc_change_power_state:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_password:  "{{ idrac_password }}"
       # GracefulRestart is applicable for idrac firmware versions below 3.30.30.30
       change_power: "GracefulRestart"

    tags:
      - graceful-restart
