---
- import_playbook: add_hosts_to_temp_group.yaml

- hosts: temp
  gather_facts: no
  tasks:

  - name: Install notepadplusplus version
    win_chocolatey:
      name: notepadplusplus
      version: '7.8'
