---
# This playbook uses the win_ping module to test connectivity to Windows hosts
- import_playbook: add_hosts_to_temp_group.yaml

- hosts: temp
  gather_facts: yes
  
  tasks:
  - name: ping
    win_ping:
