---
# Params
# "hosts": ["100.98.13.245"],
# "ansible_user": "Administrator",
# "ansible_password": "Dell@1234",
# "num_vms": 1,
# "duration": 30

- import_playbook: add_hosts_to_temp_group.yaml

- hosts: temp
  gather_facts: yes

  tasks:
  - name: Load test data
    include_vars: diskstress.yaml
  - import_tasks: tasks/download_vhdx.yaml
  - import_tasks: tasks/prov_vm.yaml
  - pause:
      prompt: "Waiting for VM to power up"
      seconds: 180
  - import_tasks: tasks/execute_on_vm.yaml
