---
- import_playbook: add_hosts_to_temp_group.yaml

- hosts: temp
  gather_facts: yes

  tasks:
  - name: Enable firewall for Domain, Public and Private profiles
    win_firewall:
      state: enabled
      profiles:
      - Domain
      - Private
      - Public
    tags: enable_firewall
    
<#    
  
  #- name: Disable firewall for Domain, Public and Private profiles
   # win_firewall:
      #state: disabled
      #profiles:
      #- Domain
      #- Private
      #- Public
    #tags: disable_firewall
    
#>
