---
- import_playbook: add_hosts_to_temp_group.yaml

- hosts: temp
  gather_facts: yes

  tasks:
  - name: Create a partition with drive letter D and size 5 GiB
    win_partition:
      drive_letter: D
      partition_size: 5 GiB
      disk_number: 1

  - name: Full format the newly created partition as NTFS and label it
    win_format:
      drive_letter: D
      file_system: NTFS
      new_label: Formatted
      full: True
