---
- import_playbook: add_hosts_to_temp_group.yaml

- hosts: temp
  gather_facts: yes

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: Output first disk size
    debug:
      var: ansible_facts.disks[0].size
